(function(){
	let srcRoot = "_resources/src/client/img/";
	let tree = {
		base:[
			"background.png",
			"black_circle.png",
			"blank.png",
			"coin.png",
			"ring_gold2.png",
			"wood_back.png"
		],
		button:[
			"bd.png",
			"bl.png",
			"cd.png",
			"cl.png",
			"gd.png",
			"gl.png",
			"pd.png",
			"pl.png"
		],
		card_enemy:[
			"type_b.png",
			"type_c.png",
			"type_g.png",
			"type_p.png",
		],
		game_result:[
			"draw.png",
			"draw_dark.png",
			"lose.png",
			"lose_dark.png",
			"win.png",
			"win_dark.png",
		],
		num_7seg:[
			"0.png",
			"1.png",
			"2.png",
			"3.png",
			"4.png",
			"5.png",
			"6.png",
			"7.png",
			"8.png",
			"9.png",
			"_off.png",
		],
		slot_pannel:{
			quad:[
				"01.png",
				"02.png",
				"03.png",
				"04.png",
				"05.png",
			],
			single:[
				"dark_01.png",
				"dark_02.png",
				"dark_03.png",
				"dark_04.png",
				"dark_05.png",
				"dark_06.png",
				"dark_07.png",
				"dark_08.png",
				"dark_09.png",
				"dark_10.png",
				"dark_11.png",
				"dark_12.png",
				"dark_13.png",
				"dark_14.png",
				"dark_15.png",
				"dark_16.png",
				"dark_17.png",
				"dark_18.png",
				"dark_19.png",
				"dark_20.png",
			],
			std:[
				"default.png"
			]
		},
	};
	let assets = new TreeParser(srcRoot,tree).parsed;
	Preloader.loadAll(assets);
})();